language: php

php:
  - 5.3.3
  - 5.4

before_install:
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install --prefer-source --dev --no-interaction
 - cd test

script:
 - ../vendor/bin/phpunit

